project:
  type: website
  output-dir: C:\Users\kb90.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Kelvin Boateng E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Academic Projects
      - href: gis_technical_labs.qmd
        text: GIS & Technical Work
      - href: work_experience.qmd
        text: Professional Experience
       
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

